### ISSUE TITLE
State of the field: other commonly-used packages

### ISSUE THREAD

**Issue by lnferris** [chadagreene/Tide-Model-Driver#10]
This is part of [JOSS review](https://github.com/openjournals/joss-reviews/issues/6018).

TMD 2.5 cites two alternative versions of the toolbox, Fortran (https://www.tpxo.net/otps) and Python (https://github.com/tsutterley/pyTMD). It is appropriate to mention these around line 27 of the paper, as you have done in README.md.

Similarly, it is probably appropriate to explain or change "The MATLAB version...no major updates...since its inception". The citation for TMD 2.5 is from 2022 which is inconsistent with the narrative that no one has touched it since its inception.

**Comment by chadagreene** [comment]
We've added mention of the Fortran and Python versions to the paper. 

We don't exactly state that TMD hasn't been touched since its inception. We say that TMD3.0 is based on the same equations that were originally implemented in Fortran in the 1990s, and that there haven't been any major updates since it was converted to MATLAB decades ago. The 2022 date associated with TMD2.5 is just the date the code was added to a repository--it had been available to the public for many years before from GitHub, and before that, from the ESR website directly.
