### ISSUE TITLE
Suggestion: TPXO coming soon

### ISSUE THREAD

**Issue by lnferris** [chadagreene/Tide-Model-Driver#12]
This is part of [JOSS review](https://github.com/openjournals/joss-reviews/issues/6018).

TPXO is a staple, and so I tried running TPXO9_atlas_v5_to_NetCDF.m and it produced the NetCDF file, but it took hours to run. Since you have the code already, would it be possible to supply the file (via Box, etc.) to users? Is the file "coming soon" an issue with QAQC or a permissions? If it is a permissions issue, could you mention the existence of TPXO9_atlas_v5_to_NetCDF.m next to "data access" on tide_model_data.md, in the interim?

**Comment by chadagreene** [comment]
Thanks for this comment. The issue of data ownership is a delicate one, and we're working toward a solution that will keep everyone happy. The TPXO9_atlas_v5_to_NetCDF.m file is available for users who are particularly dedicated, but we understand the burden it places on users. That script was originally intended to be run just once and only by me, because it's slow and requires downloading and using the rats' nest of code that is TMD2.5. We don't really want to encourage users to use TPXO9_atlas_v5_to_NetCDF.m because it requires use of a toolbox we don't own or have control over, and the reason for creating TMD3.0 was to eliminate this exact type of confusing and unnecessary effort. I could go on about this, but suffice it to say, we understand your point well and we're working hard to find a way for users to access the data without so much friction. Until then, we just have to say it's Coming Soon.

**Comment by lnferris** [comment]
I understand that you cannot provide the .nc file for now, but would like you to mention the option of using TPXO9_atlas_v5_to_NetCDF.m (if it indeed produces a correct .nc file) next to Coming Soon, because an update to TMD which doesn't support the most important tidal model (TPXO) is probably less useful than TMD2.5.

**Comment by chadagreene** [comment]
Good idea. I've made the note as suggested.

**Comment by lnferris** [comment]
"may attempt to create your own data file yourself using"

Is the world attempt used because you are not sure if the resulting file is correct, or because it is a time-intensive process?

**Comment by chadagreene** [comment]
Ha, I see what you mean. The intention was only to convey that it's time intensive, but I understand the ambiguity introduced by the word "attempt". I've fixed it now.
